### ISSUE TITLE
Deprecation warning in PHP 8.2

### ISSUE THREAD

**Issue by SeriousJ55** [wikimedia/mediawiki-libs-less.php#93]
In PHP 8.2, we get the following warning

> Warning: Undefined property: Less_Tree_Call::$unit in \lessphp\vendor\wikimedia\less.php\lib\Less\Tree\Dimension.php on line 85

When will it be fixed?

**Comment by Krinkle** [comment]
@SeriousJ55 Can you share a minimal test case to reproduce it? I have a hunch of two ways to fix it, but I'd like to pick the more minimal approach if I can confirm that it will address it.

The code in question is already covered by a test:
<https://doc.wikimedia.org/cover/mediawiki-libs-less.php/Tree/Dimension.php.html#81>

and we don't receive any deprecation warnings on the PHP 8.2 builds. The issue is specific to certain inputs. The cause is definitely in our code and not yours, but having an example will help speed up the fix.

**Comment by SeriousJ55** [comment]
Of course! Please find our less file here:
[https://www.dropbox.com/s/8ncrz6u1anzquhe/style_backoffice.less?dl=0](https://www.dropbox.com/s/8ncrz6u1anzquhe/style_backoffice.less?dl=0)

**Comment by Krinkle** [comment]
@SeriousJ55 Sorry, I didn't catch that in time. Could you share it again?

**Comment by SeriousJ55** [comment]
Sure! Here it is again: https://www.dropbox.com/s/is1ihujibrke8kt/style_backoffice.less?dl=0

**Comment by Krinkle** [comment]
@SeriousJ55 Thanks! I've reduced it to the following:

```css
.highlight {
	--margin-top: 89px;
	--margin-bottom: 25px;
	--height: calc(100% - var(--margin-top) - var(--margin-bottom));
	top: var(--margin-top);
}
```

The output:
```css
.highlight {
  --margin-top: 89px;
  --margin-bottom: 25px;
  --height: calc(100%);
  top: var(--margin-top);
}
```

The warnings:

```
bin/lessc ~/Downloads/style_backoffice.less  2>&1 | grep -E 'PHP (Notice|Warn)'
PHP Warning:  Undefined property: Less_Tree_Call::$unit in /Users/krinkle/Development/less.php/lib/Less/Tree/Dimension.php on line 85
PHP Warning:  Attempt to read property "numerator" on null in /Users/krinkle/Development/less.php/lib/Less/Tree/Dimension.php on line 85

PHP Warning:  Undefined property: Less_Tree_Call::$unit in …/less.php/lib/Less/Tree/Dimension.php on line 85
PHP Warning:  Attempt to read property "denominator" on null in …/less.php/lib/Less/Tree/Dimension.php on line 85

PHP Warning:  Undefined property: Less_Tree_Call::$unit in …/less.php/lib/Less/Tree/Dimension.php on line 85
PHP Warning:  Attempt to read property "numerator" on null in …/less.php/lib/Less/Tree/Dimension.php on line 85

PHP Warning:  Undefined property: Less_Tree_Call::$unit in …/less.php/lib/Less/Tree/Dimension.php on line 85
PHP Warning:  Attempt to read property "denominator" on null in …/less.php/lib/Less/Tree/Dimension.php on line 85
```
